
package mx.gob.imss.biometricos.ws.wssendemail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.gob.imss.biometricos.util.Constantes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//URL para QA
//@WebServiceClient(name = "SendMailServicePortBindingQSService", targetNamespace = "http://mx.gob.imss.email.model", wsdlLocation = "http://172.16.5.180:8001/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl")
//URL PRODUCCION     Verificar
// @WebServiceClient(name = "SendMailServicePortBindingQSService", targetNamespace = "http://mx.gob.imss.email.model", wsdlLocation = "http://172.16.23.201/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl")

@WebServiceClient(name = "SendMailServicePortBindingQSService", targetNamespace = "http://mx.gob.imss.email.model", wsdlLocation = Constantes.URL_GESTION_PATRONAL + "/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl")
public class SendMailServicePortBindingQSService
    extends Service
{

//    URL para QA
//    http://172.16.5.180:8001/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl
//

//    http://172.16.5.15:8001/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy
	//http://172.16.5.15:8001/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl
//  URL PRODUCCION     Verificar
	// http://172.16.23.201/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl


    private final static URL SENDMAILSERVICEPORTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDMAILSERVICEPORTBINDINGQSSERVICE_EXCEPTION;
    private final static QName SENDMAILSERVICEPORTBINDINGQSSERVICE_QNAME = new QName("http://mx.gob.imss.email.model", "SendMailServicePortBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//          URL para QA
     //      url = new URL("http://172.16.5.180:8001/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl");
        //  URL PRODUCCION     Verificar
            //url = new URL("http://172.16.23.201/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl");
        	url = new URL(Constantes.URL_GESTION_PATRONAL + "/deltaGestionPatronalService/proxy/mail/SendEmailServiceProxy?wsdl");
            
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMAILSERVICEPORTBINDINGQSSERVICE_WSDL_LOCATION = url;
        SENDMAILSERVICEPORTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public SendMailServicePortBindingQSService() {
        super(__getWsdlLocation(), SENDMAILSERVICEPORTBINDINGQSSERVICE_QNAME);
    }

    public SendMailServicePortBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMAILSERVICEPORTBINDINGQSSERVICE_QNAME, features);
    }

    public SendMailServicePortBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SENDMAILSERVICEPORTBINDINGQSSERVICE_QNAME);
    }

    public SendMailServicePortBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMAILSERVICEPORTBINDINGQSSERVICE_QNAME, features);
    }

    public SendMailServicePortBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMailServicePortBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMailServicePortType
     */
    @WebEndpoint(name = "SendMailServicePortBindingQSPort")
    public SendMailServicePortType getSendMailServicePortBindingQSPort() {
        return super.getPort(new QName("http://mx.gob.imss.email.model", "SendMailServicePortBindingQSPort"), SendMailServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMailServicePortType
     */
    @WebEndpoint(name = "SendMailServicePortBindingQSPort")
    public SendMailServicePortType getSendMailServicePortBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.gob.imss.email.model", "SendMailServicePortBindingQSPort"), SendMailServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMAILSERVICEPORTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw SENDMAILSERVICEPORTBINDINGQSSERVICE_EXCEPTION;
        }
        return SENDMAILSERVICEPORTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
