
package mx.gob.imss.biometricos.ws.wsconsultasat.service;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.gob.imss.biometricos.ws.wsconsultasat.mx_gob_imss_didt_cia_interoper_sat_pojos.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SATPatrones", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
@XmlSeeAlso({
        mx.gob.imss.biometricos.ws.wsconsultasat.mx_gob_imss_didt_cia_interoper_sat_pojos.ObjectFactory.class,
        ObjectFactory.class
})
public interface SATPatrones {


    /**
     * 
     * @param datosEntrada
     * @return
     *     returns java.mx_gob_imss_didt_cia_interoper_sat_pojos.SalidaSAT
     */
    @WebMethod
    @WebResult(targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
    @RequestWrapper(localName = "getPatron", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws", className = "mx.gob.imss.didt.cia.interoper.sat.ws.GetPatron")
    @ResponseWrapper(localName = "getPatronResponse", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws", className = "mx.gob.imss.didt.cia.interoper.sat.ws.GetPatronResponse")
    public SalidaSAT getPatron(
        @WebParam(name = "datosEntrada", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
                EntradaSAT datosEntrada);

}
