
package mx.gob.imss.biometricos.ws.wsfirmaelectronicaseg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.gob.imss.biometricos.util.Constantes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//URL QA 
//@WebServiceClient(name = "FirmaElectronicaSegService", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", wsdlLocation = "http://firmadigitalqa.imss.gob.mx/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL")
//URL PRODUCCION     Verificar 
//@WebServiceClient(name = "FirmaElectronicaSegService", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", wsdlLocation =  "https://firmadigitalssl.imss.gob.mx/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL")

//@WebServiceClient(name = "FirmaElectronicaSegService", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", wsdlLocation = Constantes.URL_FIRMA_DIGITAL + "/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL")
@WebServiceClient(name = "FirmaElectronicaSegService", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", wsdlLocation = Constantes.URL_FIRMA_DIGITAL + "/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL")
public class FirmaElectronicaSegService
    extends Service
{

    private final static URL FIRMAELECTRONICASEGSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIRMAELECTRONICASEGSERVICE_EXCEPTION;
    private final static QName FIRMAELECTRONICASEGSERVICE_QNAME = new QName("http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", "FirmaElectronicaSegService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	//URL QA 
        	//  url = new URL("http://firmadigitalqa.imss.gob.mx/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL");
        	//URL PRODUCCION     Verificar 
        //   url = new URL("https://firmadigitalssl.imss.gob.mx/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL");
        	 url = new URL(Constantes.URL_FIRMA_DIGITAL + "/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL"); 
        	 System.out.println("FirmaElectronicaSegService url: " + url);  
        	  
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRMAELECTRONICASEGSERVICE_WSDL_LOCATION = url;
        FIRMAELECTRONICASEGSERVICE_EXCEPTION = e;
    }

    public FirmaElectronicaSegService() {
        super(__getWsdlLocation(), FIRMAELECTRONICASEGSERVICE_QNAME);
    }

    public FirmaElectronicaSegService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRMAELECTRONICASEGSERVICE_QNAME, features);
    }

    public FirmaElectronicaSegService(URL wsdlLocation) {
        super(wsdlLocation, FIRMAELECTRONICASEGSERVICE_QNAME);
    }

    public FirmaElectronicaSegService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRMAELECTRONICASEGSERVICE_QNAME, features);
    }

    public FirmaElectronicaSegService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmaElectronicaSegService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirmaElectronicaSegPortType
     */
    @WebEndpoint(name = "FirmaElectronicaSegPortTypePort")
    public FirmaElectronicaSegPortType getFirmaElectronicaSegPortTypePort() {
        return super.getPort(new QName("http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", "FirmaElectronicaSegPortTypePort"), FirmaElectronicaSegPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaElectronicaSegPortType
     */
    @WebEndpoint(name = "FirmaElectronicaSegPortTypePort")
    public FirmaElectronicaSegPortType getFirmaElectronicaSegPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", "FirmaElectronicaSegPortTypePort"), FirmaElectronicaSegPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRMAELECTRONICASEGSERVICE_EXCEPTION!= null) {
            throw FIRMAELECTRONICASEGSERVICE_EXCEPTION;
        }
        return FIRMAELECTRONICASEGSERVICE_WSDL_LOCATION;
    }

}
