
package mx.gob.imss.biometricos.ws.wsfirmaelectronicaseg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirmaElectronicaSegPortType", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirmaElectronicaSegPortType {
    

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.FirmaSimpleResponseType
     */
    @WebMethod(operationName = "FirmaSimple", action = "http://idtrust.metatrust.com.mx/WsFirmaElectronicaSeg/FirmaSimple")
    @WebResult(name = "FirmaSimpleResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaSimpleResponseType firmaSimple(
            @WebParam(name = "FirmaSimpleRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
                    FirmaSimpleRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.FirmaXMLSegResponseType
     */
    @WebMethod(operationName = "FirmaXML", action = "http://idtrust.metatrust.com.mx/WsFirmaElectronicaSeg/FirmaXML")
    @WebResult(name = "FirmaXMLSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaXMLSegResponseType firmaXML(
            @WebParam(name = "FirmaXMLSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
                    FirmaXMLSegRequestType body);



    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.FirmaSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/firma")
    @WebResult(name = "FirmaSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaSegResponseType firma(
            @WebParam(name = "FirmaSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
                    FirmaSegRequestType body);



    /**
     * 
     * @param body
     * @return
     *     returns mx.com.metatrust.doctrust.wsfirmaelectronicaseg.HashSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/getHash")
    @WebResult(name = "HashSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public HashSegResponseType getHash(
            @WebParam(name = "HashSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
                    HashSegRequestType body);



}
